# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(30, 30, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 16))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(parent=self.frame)
        self.spinBox.setGeometry(QtCore.QRect(10, 40, 81, 22))
        self.spinBox.setObjectName("spinBox")
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setGeometry(QtCore.QRect(210, 30, 120, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.frame_2)
        self.doubleSpinBox.setGeometry(QtCore.QRect(10, 50, 91, 22))
        self.doubleSpinBox.setDecimals(4)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 54, 16))
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(parent=Form)
        self.frame_3.setGeometry(QtCore.QRect(10, 120, 171, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.comboBox = QtWidgets.QComboBox(parent=self.frame_3)
        self.comboBox.setGeometry(QtCore.QRect(10, 50, 121, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_3.setObjectName("label_3")
        self.frame_4 = QtWidgets.QFrame(parent=Form)
        self.frame_4.setGeometry(QtCore.QRect(200, 160, 151, 111))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label_4.setObjectName("label_4")
        self.lcdNumber = QtWidgets.QLCDNumber(parent=self.frame_4)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 50, 91, 41))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(4)
        self.lcdNumber.setProperty("value", 3.14)
        self.lcdNumber.setObjectName("lcdNumber")

        self.retranslateUi(Form)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "选择整数"))
        self.spinBox.setSuffix(_translate("Form", "个"))
        self.spinBox.setPrefix(_translate("Form", "第"))
        self.label_2.setText(_translate("Form", "选择小数"))
        self.label_3.setText(_translate("Form", "文本选择框"))
        self.label_4.setText(_translate("Form", "液晶数字显示控件"))
